color0 #1a231f
color1 #fd4663
color2 #67e4b1
color3 #5ccfd6
color4 #6690cc
color5 #93ecc7
color6 #96e4e9
color7 #f2f3f2
color8 #5b6f67
color9 #fd4663
color10 #67e4b1
color11 #5ccfd6
color12 #6690cc
color13 #93ecc7
color14 #96e4e9
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1a231f
background            #1a231f
foreground            #f2f3f2
selection_foreground  #afb6b3
selection_background  #232e2a
active_border_color   #67e4b1
inactive_border_color #232e2a
url_color             #67e4b1

active_tab_foreground   #182520
active_tab_background   #67e4b1
inactive_tab_foreground #afb6b3
inactive_tab_background #232e2a
cursor_trail_color      #afb6b3
