color0 #192024
color1 #fd4663
color2 #67b8e4
color3 #5c6ad6
color4 #70cc66
color5 #93ccec
color6 #969fe9
color7 #f2f2f3
color8 #5e6b72
color9 #fd4663
color10 #67b8e4
color11 #5c6ad6
color12 #70cc66
color13 #93ccec
color14 #969fe9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #192024
background            #192024
foreground            #f2f2f3
selection_foreground  #afb4b6
selection_background  #222b30
active_border_color   #67b8e4
inactive_border_color #222b30
url_color             #67b8e4

active_tab_foreground   #182025
active_tab_background   #67b8e4
inactive_tab_foreground #afb4b6
inactive_tab_background #222b30
cursor_trail_color      #afb4b6
