color0 #1e112c
color1 #fd4663
color2 #a167e4
color3 #d25cd6
color4 #cc669c
color5 #bc93ec
color6 #e696e9
color7 #f2f2f3
color8 #696074
color9 #fd4663
color10 #a167e4
color11 #d25cd6
color12 #cc669c
color13 #bc93ec
color14 #e696e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1e112c
background            #1e112c
foreground            #f2f2f3
selection_foreground  #b2afb6
selection_background  #28173b
active_border_color   #a167e4
inactive_border_color #28173b
url_color             #a167e4

active_tab_foreground   #1e1825
active_tab_background   #a167e4
inactive_tab_foreground #b2afb6
inactive_tab_background #28173b
cursor_trail_color      #b2afb6
