# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x111111ff
bordercolor = 0x606060ff
dropcolor = 0xaaaaaa80
splitcolor = 0xccccccff
focuscolor = 0xaaaaaaff
maximizescreencolor = 0xa7a7a7ff
urgentcolor = 0xddddddff
scratchpadcolor = 0xccccccff
globalcolor = 0x5d4545ff
overlaycolor = 0x594242ff
jump_label_decorate_fg_color = 0x828282ff
jump_label_decorate_bg_color = 0x1c1c1cff
jump_label_decorate_focus_fg_color = 0x111111ff
jump_label_decorate_focus_bg_color = 0xaaaaaaff
jump_label_decorate_border_color = 0x606060ff
group_bar_decorate_fg_color = 0x828282ff
group_bar_decorate_bg_color = 0x1c1c1cff
group_bar_decorate_focus_fg_color = 0x111111ff
group_bar_decorate_focus_bg_color = 0xaaaaaaff
group_bar_decorate_border_color = 0x606060ff
