#!/usr/bin/bash

swww-daemon &
swaybg --output "*" --image ~/.cache/wallpaper_blurred.png --mode fill &
waybar --config ~/.config/waybar/confs/blocks/config.niri.jsonc -s ~/.config/waybar/confs/blocks/style.css &
wally -r &
mpd &
nm-applet &
swaync --config ~/.config/swaync/config.json --style ~/.config/swaync/style.css &
hyprsunset &
/usr/bin/emacs --daemon &
