gui:
  border: rounded
  showIcons: false
  theme:
    activeBorderColor:
      - '#ee5396'
      - bold
    inactiveBorderColor:
      - '#636363'
    optionsTextColor:
      - '#be95ff'
    selectedLineBgColor:
      - '#262626'
    selectedLineFgColor:
      - '#f2f4f8'
    cherryPickedCommitBgColor:
      - '#42be65'
    cherryPickedCommitFgColor:
      - '#42be65'
    unstagedChangesColor:
      - '#ee5396'
    defaultFgColor:
      - '#f2f4f8'
    searchingActiveBorderColor:
      - '#be95ff'

  authorColors:
    '*': '#ee5396'

  spinner:
    frames:
     - '⠋'
     - '⠙'
     - '⠹'
     - '⠸'
     - '⠼'
     - '⠴'
     - '⠦'
     - '⠧'
     - '⠇'
     - '⠏'
git:
  parseEmoji: true
