gui:
  theme:
    activeBorderColor:
      - "#7367e4"
      - bold
    inactiveBorderColor:
      - "#a35cd6"
    searchingActiveBorderColor:
      - "#cd65c3"
      - bold
    optionsTextColor:
      - "#afafb6"
    selectedLineBgColor:
      - "#241e5c"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#afafb6"
    cherryPickedCommitBgColor:
      - "#cd65c3"
    markedBaseCommitFgColor:
      - "#cd65c3"
    markedBaseCommitBgColor:
      - "#fd4663"
    unstagedChangesColor:
      - "#fd4663"
    defaultFgColor:
      - "#f2f2f3"
  border: rounded
  showIcons: false
  spinner:
    frames:
     - '⠋'
     - '⠙'
     - '⠹'
     - '⠸'
     - '⠼'
     - '⠴'
     - '⠦'
     - '⠧'
     - '⠇'
     - '⠏'
git:
  parseEmoji: true
