gui:
  border: rounded
  showIcons: false
  theme:
    activeBorderColor:
      - '#fd4663'
      - bold
    inactiveBorderColor:
      - '#66686f'
    optionsTextColor:
      - '#9391a1'
    selectedLineBgColor:
      - '#2f3237'
    selectedLineFgColor:
      - '#f2f2f3'
    cherryPickedCommitBgColor:
      - '#9192a1'
    cherryPickedCommitFgColor:
      - '#9192a1'
    unstagedChangesColor:
      - '#fd4663'
    defaultFgColor:
      - '#f2f2f3'
    searchingActiveBorderColor:
      - '#9391a1'

  authorColors:
    '*': '#fd4663'

  spinner:
    frames:
     - '⠋'
     - '⠙'
     - '⠹'
     - '⠸'
     - '⠼'
     - '⠴'
     - '⠦'
     - '⠧'
     - '⠇'
     - '⠏'
git:
  parseEmoji: true
