#!/usr/bin/bash

swww-daemon &
# hyprpaper &
waybar --config ~/.config/waybar/confs/blocks/config.jsonc -s ~/.config/waybar/confs/blocks/style.css &
wally -r &
mpd &
nm-applet &
swaync --config ~/.config/swaync/config.json --style ~/.config/swaync/style.css &
elephant &
walker --gapplication-service &
hyprsunset &
