[colors]
background = '#24273a'
foreground = '#cad3f5'

cursor_bg = '#7dc4e4'
cursor_fg = '#24273a'
cursor_border = '#7dc4e4'

selection_bg = '#1f4b6b'
selection_fg = '#cad3f5'

ansi = ['#1e2030', '#ff72a0', '#72e47e', '#fff672', '#63b4d8', '#124e69', '#7dc4e4', '#e1eaef']
brights = ['#899094', '#ff9fbe', '#a5ffaf', '#fff9a5', '#9adcfa', '#aee5ff', '#cbeeff', '#f8fdff']
