[colors]
background = '#16161e'
foreground = '#a9b1d6'

cursor_bg = '#7dcfff'
cursor_fg = '#16161e'
cursor_border = '#7dcfff'

selection_bg = '#2f334d'
selection_fg = '#a9b1d6'

ansi = ['#1a1b26', '#ff709d', '#7dff8c', '#fff670', '#5ebbf2', '#074d76', '#7dcfff', '#eff9ff']
brights = ['#99a1a5', '#ff9dbc', '#a4ffae', '#fff9a4', '#90d6ff', '#a4ddff', '#c4e9ff', '#f8fcff']
