[colors]
ansi = [
    "#1c1e21",
    "#fd4663",
    "#9391a1",
    "#9192a1",
    "#9ea3ad",
    "#bcbac4",
    "#babbc4",
    "#f2f2f3",
]
background = "#1c1e21"
brights = [
    "#66686f",
    "#fd4663",
    "#9391a1",
    "#9192a1",
    "#9ea3ad",
    "#bcbac4",
    "#babbc4",
    "#f2f2f3",
]
cursor_bg = "#f2f2f3"
cursor_border = "#f2f2f3"
cursor_fg = "#1c1e21"
foreground = "#f2f2f3"
selection_bg = "#26282c"
selection_fg = "#b0b2b5"

[metadata]
name = "Noctalia"
