[colors.primary]
background = '#1a231f'
foreground = '#f2f3f2'
 
[colors.cursor]
text = '#f2f3f2'
cursor = '#afb6b3' 
 
[colors.vi_mode_cursor]
text = '#1a231f'
cursor = '#67e4b1' 
 
[colors.search.matches]
foreground = '#232e2a' 
background = '#6690cc' 
 
[colors.search.focused_match]
foreground = '#232e2a' 
background = '#67e4b1' 
 
[colors.footer_bar]
foreground = '#232e2a' 
background = '#e3e8e6' 
 
[colors.hints.start]
foreground = '#232e2a' 
background = '#5ccfd6' 
 
[colors.hints.end]
foreground = '#232e2a' 
background = '#5ccfd6' 
 
[colors.selection]
text = '#1a231f'
background = '#67e4b1'
 
 
[colors.normal]
black = '#181818' 
red = '#fd4663' 
green = '#67e4b1' 
yellow = '#33996f' 
blue = '#67e4b1' 
magenta = '#6690cc' 
cyan = '#5ccfd6' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 