[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml"
]

live_config_reload = true

[window]
dynamic_padding = true
padding = { x = 10, y = 10 }

[font]
normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
bold = { family = "FantasqueSansM Nerd Font", style = "Bold" }
italic = { family = "FantasqueSansM Nerd Font", style = "Italic" }
bold_italic = { family = "FantasqueSansM Nerd Font", style = "Bold Italic" }
size = 14
builtin_box_drawing = true 
