[colors.primary]
background = '#101010'
foreground = '#dcdcdc'

[colors.selection]
text = '#dcdcdc'
background = '#3f3f3f'

[colors.cursor]
text = '#101010'
cursor = '#5e5e5e'

[colors.normal]
black   = '#161616'
red     = '#c16b68'
green   = '#5c8f4e'
yellow  = '#9f8e47'
blue    = '#828282'
magenta = '#2b2b2b'
cyan    = '#5e5e5e'
white   = '#898181'

[colors.bright]
black   = '#7e7878'
red     = '#ac6b6b'
green   = '#6f9963'
yellow  = '#bfb27c'
blue    = '#676767'
magenta = '#7a7a7a'
cyan    = '#838383'
white   = '#b8b4b4'
